### ISSUE TITLE
Skill Editor Opens really slow

### ISSUE THREAD

**Issue by DaLeberkasPepi** [d2k2-git/D3Helper.Public#9]
Like in the titel mentioned. Since this version the Skill Editor needs up 10s and more to open

**Comment by d2k2-git** [comment]
What is the date of yor d3helper.exe ? This bug has been fixed already

**Comment by DaLeberkasPepi** [comment]
I thought I've updated to the newest version I at least downloaded it, but it shows the version number of the old version. I'll check it out when I get home

**Comment by DaLeberkasPepi** [comment]
The new version fixed that problem but pls update the version number of the d3helper window. It still shows V17.03.24 despite the fact that V17.04.18 ist running
